-- local distantLandConfig = require("colossus.distantLandConfig")

-- local function onCellChanged(e)
--     local isElsweyr = e.cell and e.cell.id == "Elsweyr"
--     local wasElsweyr = e.previousCell and e.previousCell.id == "Elsweyr"
--     if isElsweyr and not wasElsweyr then
--         distantLandConfig.setEnabled(true)
--     elseif wasElsweyr and not isElsweyr then
--         distantLandConfig.setEnabled(false)
--     end
--     -- TODO: Do we handle the case where PC enters the cell, then reloads to a different save?
-- end
-- event.register("cellChanged", onCellChanged)
